packages:
  - webui

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@opentray/ext-webview": link:../opentray/packages/ext-webview
  opentray: link:../opentray/packages/cli
